services:
  oservice-builder:
    build: 
      context: .
      args:
        - BUILD_MODE=release
        - UNET_MODULE_STEAM
    container_name: oservice_compiler
    volumes:
      - ./build:/build/out
